export const MAIN_ACTION = 'MAIN_ACTION'

export const SET_BREADCRUBMBS = 'SET_BREADCRUBMBS'
export const FETCH_BREADCRUBMBS_SUCCESS = 'FETCH_BREADCRUBMBS_SUCCESS'
export const FETCH_BREADCRUBMBS_ERROR = 'FETCH_BREADCRUBMBS_ERROR'
